Synchornous ADC API
UPB-CS-OpenSourceUpstream/libtock-rs pull request #28
Opened 2023-04-14 00:19 UTC by AnneOnciulescu

Started working on [#10](https://github.com/UPB-CS-OpenSourceUpstream/libtock-rs/issues/10). Still a draft, a lot more to be done.

2023-04-18 03:33 UTC, alexandruradovici reviewed
I would start only by providing the simple read API, that reads one single value.

2023-05-05 08:48 UTC, alexandruradovici commented
@AnneOnciulescu any progress?

2023-05-09 10:11 UTC, alexandruradovici requested changes
Looks good, just make the changes and let's send the first version to upstream.

2023-05-09 10:11 UTC, alexandruradovici commented on apis/adc/src/lib.rs
> +            }
Use the ?, similar to https://github.com/DanutAldea/libtock-rs/blob/b70eb0cbe1766a37585472235e77f755a7c12786/apis/ambient_light/src/lib.rs#L45-L46

2023-05-09 10:32 UTC, alexandruradovici submitted a review, later dismissed
Looks good, a small fix in the sample and send it to upstream.

2023-05-09 10:32 UTC, alexandruradovici commented on examples/adc.rs
> +    }
```suggestion
    if Adc::exists().is_err() {
        writeln!(Console::writer(), "adc driver unavailable").unwrap();
        return;
    }
```

2023-05-09 11:09 UTC, alexandruradovici commented on apis/adc/src/lib.rs
> +    // pub fn stop_sampling()
Delete this.

2023-05-09 11:10 UTC, alexandruradovici approved these changes, later dismissed

2023-05-09 11:16 UTC, AnneOnciulescu commented
[tock#471](https://github.com/tock/libtock-rs/pull/471)

2023-05-19 16:12 UTC, merged