Ambient Light API
UPB-CS-OpenSourceUpstream/libtock-rs pull request #29
Opened 2023-04-21 16:31 UTC by DanutAldea

Fixes [#26](https://github.com/UPB-CS-OpenSourceUpstream/libtock-rs/issues/26)
Heavily inspired from the work done [here](https://github.com/UPB-CS-OpenSourceUpstream/libtock-rs/pull/5)
Added the api, an exemple, fake driver and tests.

2023-04-24 10:17 UTC, alexandruradovici requested changes
Just simplify the example as suggested and this is good to go. Write a PR message.

2023-04-24 10:17 UTC, alexandruradovici commented on examples/ambient_light.rs
> +    }
```suggestion
    if AmbientLight::exists().is_err() {
            writeln!(Console::writer(), "ambient light driver unavailable").unwrap();
            return;
    }
```

2023-04-25 07:37 UTC, DanutAldea commented
### Pull Request Overview
This PR adds an Ambient Light API, which includes:

- function for checking the existence of the driver
- functions for initating readings of the luminance, registering and unregistering a listener
- function for synchronous reading of values of luminance and 2 public functions for easier use of the API
- unit tests

Alongside the API, this PR adds a fake driver (and unit tests for it) for testing the API.

### Testing Strategy
This pull request was tested using unit tests made specifically for this API and fake driver.

### TODO or Help Wanted
This pull request still needs feedback / code review.
Help is needed to test this on a board, as I do not have access to one which has a light sensor module

2023-04-25 07:40 UTC, alexandruradovici submitted a review, later dismissed
Looks really good, please send it to upstream and place a link to it. Hudson offered to test if it works on imix, you can tag him in the pull request message.

2023-04-25 08:49 UTC, DanutAldea commented
https://github.com/tock/libtock-rs/pull/465

2023-05-19 16:12 UTC, merged