Temperature API
UPB-CS-OpenSourceUpstream/libtock-rs pull request #5
Opened 2022-12-14 01:12 UTC by alexandruCarp

Implemented the Temperature API and an example application.
The example application is similar to the [sensors example](https://github.com/tock/libtock-c/tree/master/examples/sensors) in libtock-c.

TODO: Add unit tests

2022-12-16 10:36 UTC, alexandruradovici reviewed
Looks ok.

2023-01-03 16:29 UTC, alexandruradovici commented
Hi, any updates regarding the writing of unit tests?

2023-01-03 20:14 UTC, alexandruCarp commented
Hi! Sorry for this long break, to be honest I didn't really know how this testing part works and postponed this for too long. I don't want to give up though, so if it's not too late I will try to get it done by the end of this week. I guess taking the tests for leds/buttons APIs as an example should be ok, right?

2023-01-04 22:19 UTC, alexandruradovici commented
Yes, looking at LED and GPIO should be the staring point. Briefly, you should:
- write a fake temperature driver 
- write tests for it
- write tests that use the fake kernel and driver to test your user space driver library

2023-01-07 09:49 UTC, alexandruCarp commented
I don't know how to test the "read_temperature_sync()" function as I would have to schedule an upcall after the "read_temp" command, but before yield, and they both happen in that function. I thought that maybe I should modify the fake driver to schedule an upcall on the call of the command, but it doesn't seem right for the upcall to be scheduled immediately (the driver would never be busy). Any suggestions?

2023-01-07 11:41 UTC, alexandruradovici commented
The `sync` function should return the temperature, as simple as:

```rust
assert_eq! (Temperature::read_temperature_sync(), Ok(expected_temperature_value));
```

2023-01-07 11:46 UTC, alexandruradovici requested changes

2023-01-07 11:46 UTC, alexandruradovici commented on apis/temperature/src/lib.rs
> +    pub fn read_temperature_sync() -> Result<u32, ErrorCode> {
```suggestion
    pub fn read_temperature_sync() -> Result<isize, ErrorCode> {
```

The temperature is reported in 100s of centigrade, meaning that 20.6 deg is 2060. The temperature can be negative, but as upcall values are always `usize`, the driver makes a typecast

https://github.com/tock/tock/blob/500caa5e882b7efe40158849fb489205f07c6a2e/capsules/src/temperature.rs#L119

that the library should reverse.

2023-01-07 13:42 UTC, alexandruCarp commented
> The `sync` function should return the temperature, as simple as:
> 
> ```rust
> assert_eq! (Temperature::read_temperature_sync(), Ok(expected_temperature_value));
> ```

Right, and it works as expected with the real driver on the board. However, with the fake driver it says `yield-wait called with no queued upcall` because if I call the [set_value](https://github.com/alexandruCarp/libtock-rs/blob/ad9b1a1e0f840045551d61b29e287854253ccdfb/unittest/src/fake/temperature/mod.rs#L23) function before read_sync it does not enqueue any upcall as no subscribe has been made yet. Most likely the fake driver has a problem.

2023-01-08 10:08 UTC, alexandruradovici requested changes

2023-01-08 10:08 UTC, alexandruradovici commented on unittest/src/fake/temperature/tests.rs
> +}
Add newline

2023-01-08 10:13 UTC, alexandruradovici commented
> Right, and it works as expected with the real driver on the board. However, with the fake driver it says `yield-wait called with no queued upcall` because if I call the [set_value](https://github.com/alexandruCarp/libtock-rs/blob/ad9b1a1e0f840045551d61b29e287854253ccdfb/unittest/src/fake/temperature/mod.rs#L23) function before read_sync it does not enqueue any upcall as no subscribe has been made yet. Most likely the fake driver has a problem.

I think you have to add a different `set_value` function, like `set_value_sync` that does not call an upcall immediately, but calls it when it receives the read command.

2023-01-09 09:18 UTC, alexandruradovici requested changes

2023-01-09 09:18 UTC, alexandruradovici commented on unittest/src/fake/temperature/mod.rs
> +    upcall_on_command: Cell<Option<i32>>,
Please add a comment explaining why this is required, I assume others will have this issue.

2023-01-09 12:51 UTC, alexandruradovici commented on apis/temperature/src/lib.rs
> +    /// initiate a syncronous temperature mesurement
```suggestion
    /// Initiate a syncronous temperature mesurement.
```

2023-01-09 12:52 UTC, alexandruradovici commented on apis/temperature/src/lib.rs
> +    /// initiate a temperature measurement used both for syncronous and asyncronous readings
```suggestion
    /// Initiate a temperature measurement.
    ///
    /// This function is used both for synchronous and asynchronous readings
```

2023-01-09 12:57 UTC, alexandruradovici requested changes
Write a comment with the pull request message (use the pull request template from Tock) and this should be ready for sending to upstream Tock.

2023-01-09 12:57 UTC, alexandruradovici commented on apis/temperature/src/lib.rs
> +    /// initiate a syncronous temperature mesurement
Please mention the measuring unit that the temperature is returned in (hundreds of centigrades).

2023-01-09 12:57 UTC, alexandruradovici commented on examples/temperature.rs
> +                writeln!(Console::writer(), "Temperature: {}*C\n", temp_val / 100).unwrap()
```suggestion
                writeln!(Console::writer(), "Temperature: {}.{}*C\n", temp_val / 100, temp_val % 100).unwrap()
```

2023-01-09 17:27 UTC, alexandruradovici commented
Please run `cargo fmt` to format the source.

2023-01-09 22:21 UTC, alexandruCarp commented
> Write a comment with the pull request message (use the pull request template from Tock) and this should be ready for sending to upstream Tock.

### Pull Request Overview

This pull request adds:
- a Temperature API, similar to the [libtock-c version](https://github.com/tock/libtock-c/blob/master/libtock/temperature.h). The API provides a function that simulates a synchronous temperature reading and also functions to initiate a reading, register/ unregister a listener and check for driver existence. 
- an example app which samples the temperature sensor every 2 seconds and prints the measured temperature.
- a `fake` temperature driver, for testing purposes.
- unit tests for the fake driver and for the user space library

### Testing Strategy

This pull request was tested with the unit tests and by running the example app on a microbit v2 board.

### TODO or Help Wanted

Feedback is much appreciated.

### Documentation Updated

- [x] no updates are required.

### Formatting

- [ ] Ran `make prepush`.

2023-01-10 19:54 UTC, alexandruCarp commented
Should I open a pull request to upstream Tock now?

2023-01-10 20:49 UTC, alexandruradovici commented
Please fix the clippy issue and after that you can send the pull request.

2023-01-12 20:09 UTC, alexandruCarp commented
Opened PR tock/libtock-rs#451.

2023-01-13 10:53 UTC, alexandruradovici commented
Please run `make prepush` and if it works, check the `ran make prepush` checkbox.

2023-01-13 11:53 UTC, alexandruCarp commented
> Please run `make prepush` and if it works, check the `ran make prepush` checkbox in both PRs.

There is no `prepush` rule in [libtock-rs/Makefile](https://github.com/UPB-CS-OpenSourceUpstream/libtock-rs/blob/master/Makefile). Am I missing something?

2023-01-13 11:55 UTC, alexandruradovici commented
> > Please run `make prepush` and if it works, check the `ran make prepush` checkbox in both PRs.
> 
> There is no `prepush` rule in [libtock-rs/Makefile](https://github.com/UPB-CS-OpenSourceUpstream/libtock-rs/blob/master/Makefile). Am I missing something?

You are right, there is no PR template. Please just delete that form the pull request message.

2023-01-13 14:42 UTC, alexandruradovici submitted a review, later dismissed

2023-02-05 19:24 UTC, alexandruradovici commented
@alexandruCarp Please select a timeslot for the interview https://doodle.com/meeting/participate/id/eZ8gOOEb.

2023-02-08 16:56 UTC, closed without merging

2023-02-08 16:56 UTC, alexandruradovici commented
Merged in upstream.